baseURL = "https://content.iriss.org.uk/outcomes-covid-stories"
languageCode = "en-gb"
title = "A shared experience: outcomes for people through the COVID-19 pandemic"
theme = ["hugo-notice", "iriss-course"]
verbose = true
copyrighthtml = "Copyright &#xA9; 2017 John Doe. All Rights Reserved."
menu = "main"
googleAnalytics = "UA-814723-1"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "404"]
publishDir = "docs"
enableInlineShortcodes = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[social]
  twitter = "irissorg"

[params]
  description = "What has the COVID-19 crisis has meant for outcomes for people"
  images = ["images/tw-card-00.png"]
  IrissCourseAuthors  = "Ellen Daly and Emma Miller"
  IrissPublishDate = "May 2021"
  IrissCourseYearReleased = "2021"
  IrissHomeTitle = "A shared experience: outcomes for people through the COVID-19 pandemic"
  IrissDescription = "What has the COVID-19 crisis has meant for outcomes for people"

[markup.tableOfContents]
  endLevel = 2

[privacy]
   [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
